# Generated by Django 3.2.4 on 2021-06-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210628_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(default='anything'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='anything'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(default='anything'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(default='anything'),
        ),
    ]
